- name: update_mandb
  become: yes  
  command: mandb

- name: update_locales
  become: yes 
  command: locale-gen

- name: "Neovim | Copy configuration files to the target directory"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    remote_src: no