- name: update_mandb
  become: yes  # Likely needed to update mandb, which requires root privileges
  command: mandb

- name: update_locales
  become: yes  # This is usually required for locale updates
  command: locale-gen
