---
- name: Deploy custom .bashrc
  copy:
    src: "{{ role_path }}/config/.bashrc"
    dest: "/home/{{ ansible_user }}/.bashrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Deploy custom .bash_profile
  copy:
    src: "{{ role_path }}/config/.bash_profile"
    dest: "/home/{{ ansible_user }}/.bash_profile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Deploy custom bash scripts
  copy:
    src: "{{ role_path }}/config/my_script.sh"
    dest: "/usr/local/bin/my_script.sh"
    owner: "root"
    group: "root"
    mode: '0755'
