---
- name:  bash  | install programs
  become: true
  ansible.builtin.package:
    name: bat
    state: present

- name:  bash  |  .bash_aliases is present in the user's home directory
  ansible.builtin.copy:
    src: .bash_aliases
    dest: "/home/{{ ansible_user_id }}/.bash_aliases"
    mode: '0644'
    force: yes

- name:  bash  |  .bash_logout is present in the user's home directory
  ansible.builtin.copy:
    src: .bash_logout
    dest: "/home/{{ ansible_user_id }}/.bash_logout"
    mode: '0644'
    force: yes

- name: bash  |  .bashrc is present in the user's home directory
  ansible.builtin.copy:
    src: .bashrc
    dest: "/home/{{ ansible_user_id }}/.bashrc"
    mode: '0644'
    force: yes

- name: bash  |  .profile is present in the user's home directory
  ansible.builtin.copy:
    src: .profile
    dest: "/home/{{ ansible_user_id }}/.profile"
    mode: '0644'
    force: yes
