---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  roles:
    - nvim
    - bash
    - tmux
  tasks:
    - name: Install packages on Arch Linux
      ansible.builtin.package:
        name:
          - tmux
          - neovim
          - neofetch
          - bash-completion
          # - noto-fonts
        state: present
        use: pacman
      when: ansible_os_family == "Archlinux"

    - name: Install packages on Ubuntu
      ansible.builtin.package:
        name:
          - htop
          - tmux
          - neofetch
          # - fonts-noto
        state: present
        use: apt
      when: ansible_os_family == "Debian"