---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Install packages on Arch Linux
      ansible.builtin.package:
        name:
          - htop
          - tmux
          - neovim
          - neofetch
          - noto-fonts
        state: present
        use: pacman
      when: ansible_os_family == "Archlinux"

    - name: Install packages on Ubuntu
      ansible.builtin.package:
        name:
          - htop
          - tmux
          - neovim
          - neofetch
          - fonts-noto
        state: present
        use: apt
      when: ansible_os_family == "Debian"

    - name: Copy wallpaper
      ansible.builtin.copy:
        src: static/wallpaper.jpg
        dest: /usr/local/share/wallpapers/wallpaper.jpg
        owner: root
        group: root
        mode: '0644'
