- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    default_roles: []

  tasks: 
    - name: Dynamically list all roles in the 'roles' directory
      ansible.builtin.shell: ls -d roles/*/ | xargs -n 1 basename
      register: roles_output
      changed_when: false

    - name: Set dynamic roles fact
      ansible.builtin.set_fact:
        dynamic_roles: "{{ roles_output.stdout_lines }}"

    - name: Install packages conditionally
      ansible.builtin.package:
        name: "{{ item.packages }}"
        state: present
      become: true
      loop:
        - { os_family: "Archlinux", packages: [ "tmux", "neofetch", "tree", "bash-completion", "noto-fonts" ] }
        - { os_family: "Debian", packages: [ "htop", "tree", "tmux", "neofetch", "fonts-noto" ] }
      when: ansible_os_family == item.os_family

    - name: Run dynamically discovered roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ dynamic_roles }}"
      when: dynamic_roles is defined and dynamic_roles | length > 0
