---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  roles:
    - nvim
  tasks:
    - name: Install packages on Arch Linux
      ansible.builtin.package:
        name:
          - htop
          - tmux
          - neovim
          - neofetch
          - noto-fonts
        state: present
        use: pacman
      when: ansible_os_family == "Archlinux"

    - name: Install packages on Ubuntu
      ansible.builtin.package:
        name:
          - htop
          - tmux
          - neovim
          - neofetch
          - fonts-noto
        state: present
        use: apt
      when: ansible_os_family == "Debian"
    
    - name: ensure wallpaper dir exists
      file: 
        path: /home/.local/share/wallpapers
        state:  directory
        owner:  root
        group:  root
        mode: '0755' 

    - name: Copy wallpaper
      ansible.builtin.copy:
        src: static/wallpaper.jpg
        dest: /home/al/.local/share/wallpapers/wallpape.jpg
        owner: root
        group: root
        mode: '0644'
