---
- name: "tmux | install tmux"
  ansible.builtin.package:
    name: tmux
    state: present
  become: true

- name: "tmux | install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/{{ ansible_user_id }}/.config/tmux/plugins/tpm

- name: "tmux | Configure tmux"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "/home/{{ ansible_user_id }}/.config/tmux"
    force: true
    remote_src: no