- name: sway
  tags: desktop
  block:
    - name: ensure wallpaper dir exists
      file:
        path: /home/{{ ansible_user_id }}/.local/share/wallpapers
        state: directory
        force: yes

    - name: copy wallpaper
      ansible.builtin.copy:
        src: wallpaper.jpg
        dest: /home/{{ ansible_user_id }}/.local/share/wallpapers/wallpaper.jpg
        force: yes

    - name: ensure config dir exists
      file:
        path: /home/{{ ansible_user_id }}/.config/sway
        state: directory
        force: yes

    - name: copy sway config
      ansible.builtin.copy:
        src: config
        dest: "/home/{{ ansible_user_id }}/.config/sway/config"
        force: yes