---
- name: Download the latest Neovim release tarball
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz
    mode: '0644'

- name: Remove existing Neovim installation
  ansible.builtin.file:
    path: /opt/nvim
    state: absent
    become: yes

- name: Extract Neovim tarball to /opt
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes
    become: yes
    extra_opts: [--strip-components=1]
  register: unarchive_result

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: /tmp/nvim-linux64.tar.gz
    state: absent
    become: yes
  when: unarchive_result.changed

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "/home/{{ ansible_user }}/.config/nvim"
    state: directory

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "/home/{{ ansible_user }}/.config/nvim"
    state: link
    force: true
