- name: Download the latest Neovim tar.gz
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz

- name: Remove existing Neovim directory
  ansible.builtin.file:
    path: /opt/nvim
    state: absent
    become: yes

- name: Extract Neovim tar.gz to /opt
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes
    extra_opts: [--strip-components=1]
    become: yes

- name: Remove the downloaded Neovim tar.gz
  ansible.builtin.file:
    path: /tmp/nvim-linux64.tar.gz
    state: absent