---
- name: install nvim on ubuntu
  block:
    - name: Download latest nvim release
      get_url:
        url: 'https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz'
        dest: /tmp/nvim-linux64.tar.gz
        mode: '0755'
        owner: root
      register: nvim_release

    - name: Make sure that we start clean
      file:
        path: '/tmp/nvim-linux64/'
        state: absent

    - name: Unpack nvim release
      ansible.builtin.unarchive:
        src: /tmp/nvim-linux64.tar.gz
        dest: /tmp/
        decrypt: False
        remote_src: True

    - name: Clean-up previous nvim install
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /usr/bin/nvim
        - /usr/lib/nvim/
        - /usr/share/nvim/
        - /usr/share/applications/nvim.desktop
        - /usr/share/icons/hicolor/128x128/apps/nvim.png
        - /usr/share/locale/en_GB/LC_MESSAGES/nvim.mo
        - /usr/share/man/man1/nvim.1

    - name: Install latest nvim release
      copy:
        src: '/tmp/nvim-linux64/{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: '{{ item.mode }}'
        owner: root
        remote_src: True
        force: True
      with_items:
        - { src: 'bin/nvim' , dest: '/usr/bin/nvim' , mode: 'a+x'}
        - { src: 'lib/nvim/parser' , dest: '/usr/lib/nvim/' , mode: '0755'}
        - { src: 'man/man1/nvim.1' , dest: '/usr/share/man/man1/nvim.1' , mode: '0644'}
        - { src: 'share/applications/nvim.desktop' , dest: '/usr/share/applications/nvim.desktop' , mode: '0644'}
        - { src: 'share/icons/hicolor/128x128/apps/nvim.png', dest: '/usr/share/icons/hicolor/128x128/apps/nvim.png' , mode: '0644'}
        - { src: 'share/locale/en_GB/LC_MESSAGES/nvim.mo' , dest: '/usr/share/locale/en_GB/LC_MESSAGES/nvim.mo' , mode: '0644'}
        - { src: 'share/nvim/runtime' , dest: '/usr/share/nvim/' , mode: '0755'}
      # notify:
      #   - update_mandb
      #   - update_locales

    - name: Update default editor, use nvim for everything
      command:
        cmd: "{{ item }}"
      become: True
      with_items:
        - 'update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 1'
        - 'update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 1'
        - 'update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 1'
        - 'update-alternatives --set editor /usr/bin/nvim'
        - 'update-alternatives --set vi /usr/bin/nvim'
        - 'update-alternatives --set vim /usr/bin/nvim'